BUILD_DIR = build
include $(N64_INST)/include/n64.mk

PYTHON ?= python3

src = living-worlds.c

# Scene assets are generated by our custom converter (mksprite is deliberately
# not used: it would re-quantize/remap palette indices, destroying the exact
# index ordering that color cycling depends on). Run `make fetch` once to
# download all 22 scenes into scenes/*.js; each is then converted to a
# filesystem/*.lw and bundled into the ROM.
scene_files := $(wildcard scenes/*.js)
assets_conv := $(patsubst scenes/%.js,filesystem/%.lw,$(scene_files))

# If no scenes have been fetched yet, provide instructions to fetch them.
ifeq ($(assets_conv),)
ifeq ($(filter clean scenes,$(MAKECMDGOALS)),)
$(error no scenes/ found - run 'make scenes' (or tools/fetch_scenes.sh) first)
endif
endif

all: living-worlds.z64

scenes:
	bash tools/fetch_scenes.sh

filesystem/%.lw: scenes/%.js tools/convert_scene.py
	@mkdir -p $(dir $@)
	@echo "    [SCENE] $@"
	@$(PYTHON) tools/convert_scene.py -o $@ $<

$(BUILD_DIR)/living-worlds.dfs: $(assets_conv)
$(BUILD_DIR)/living-worlds.elf: $(src:%.c=$(BUILD_DIR)/%.o)

living-worlds.z64: N64_ROM_TITLE="Living Worlds"
living-worlds.z64: $(BUILD_DIR)/living-worlds.dfs

clean:
	rm -rf $(BUILD_DIR) filesystem living-worlds.z64

-include $(wildcard $(BUILD_DIR)/*.d)

.PHONY: all clean scenes
