BUILD_DIR = build
include $(N64_INST)/include/n64.mk

PYTHON ?= python3

src = living-worlds.c

# Scene assets are generated by our custom converter (mksprite is deliberately
# not used: it would re-quantize/remap palette indices, destroying the exact
# index ordering that color cycling depends on). Run `make scenes` once to
# download all 22 scenes into scenes/*.js; each is then converted to a
# filesystem/*.lw and bundled into the ROM. Per-scene metadata (title, audio,
# volume, palette remap) is read from scenes.json -- the committed scene
# catalog (regenerated from upstream by tools/fetch_catalog.py).
scene_files := $(wildcard scenes/*.js)
assets_lw := $(patsubst scenes/%.js,filesystem/%.lw,$(scene_files))

# Ambient audio loops: 13 shared MP3s from the reference demo, converted to
# Opus-compressed .wav64 (streamed from ROM by wav64_open / wav64_play). Run
# `make sounds` once to populate sounds/*.mp3.
sound_files := $(wildcard sounds/*.mp3)
assets_wav  := $(patsubst sounds/%.mp3,filesystem/%.wav64,$(sound_files))

# If no scenes have been fetched yet, provide instructions to fetch them.
ifeq ($(assets_lw),)
ifeq ($(filter clean scenes sounds,$(MAKECMDGOALS)),)
$(error no scenes/ found - run 'make scenes' (or tools/fetch_scenes.py) first)
endif
endif

all: living-worlds.z64

scenes:
	@$(PYTHON) tools/fetch_scenes.py

sounds:
	@$(PYTHON) tools/fetch_sounds.py

scenes/%.lw: scenes/%.js scenes.json tools/convert_scene.py
	@echo "    [SCENE] $@"
	@$(PYTHON) tools/convert_scene.py -o $@ $<

filesystem/%.lw: scenes/%.lw
	@mkdir -p $(dir $@)
	@$(N64_INST)/bin/mkasset --compress 1 --window 256 \
	    --output $(dir $@) $< >/dev/null

filesystem/%.wav64: sounds/%.mp3
	@mkdir -p $(dir $@)
	@echo "    [SOUND] $@"
	@$(N64_AUDIOCONV) --wav-mono --wav-compress 3 \
	    --wav-loop true -o $(dir $@) $< >/dev/null

$(BUILD_DIR)/living-worlds.dfs: $(assets_lw) $(assets_wav)
$(BUILD_DIR)/living-worlds.elf: $(src:%.c=$(BUILD_DIR)/%.o)

living-worlds.z64: N64_ROM_TITLE="Living Worlds"
living-worlds.z64: $(BUILD_DIR)/living-worlds.dfs

clean:
	rm -rf $(BUILD_DIR) filesystem living-worlds.z64

-include $(wildcard $(BUILD_DIR)/*.d)

.PHONY: all clean scenes sounds
